- name: init
  hosts: all
  pre_tasks:
    - name: import check Ansible version task
      import_tasks: utils/assert-ansible-version.yaml
  tags:
    - always

- name: stop gunicorn
  hosts: all
  tasks:
    - name: stop Django service
      systemd:
        name: "{{ service_name }}"
        state: stopped
      become: yes
  tags:
    - gunicorn
    - project

- name: stop memcached
  hosts: all
  tasks:
    - name: stop memcached
      systemd:
        name: memcached
        state: stopped
      become: yes
  tags:
    - memcached

- name: stop nginx
  hosts: all
  tasks:
    - name: stop nginx
      systemd:
        name: nginx
        state: stopped
      become: yes
  tags:
    - nginx
    - project
